name: Refinery News Bot (Daily 08:00 KST)

on:
  schedule:
    - cron: '0 23 * * *'   # 08:00 KST
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run news pipeline
        run: |
          python news_pipeline.py --once
