name: Refinery News Bot (Daily 08:00 KST)
on:
  schedule:
    - cron: '0 23 * * *'   # 매일 08:00 KST
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Run news pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          export TZ=Asia/Seoul
          source .venv/bin/activate
          python news_pipeline.py --once
